### ISSUE TITLE
Reversed characters in isLandscape=false 

### ISSUE THREAD

**Issue by poundy** [veccsolutions/Vecc.Netduino.Drivers.Ili9341#2]
With (at least) the LCD that I have, when I use isLandscape=false in the sandpit app, the text renders backwards. Per character, the pixels are reversed.  I haven't looked in depth to see how yet to correct the behavior, but thought I'd report it here first.

**Comment by veccsolutions** [comment]
Interesting, my LCD screen rendered correctly, though it was a while ago that I checked that part. We could add a public property in the Driver.DrawChar file, named something like ReverseCharacterImage, if it's true, the filling of the pixel array inside of the for loop would then be reversed. That's my guess anyways.

The reason I suggest inside of the Driver.DrawChar is because it is only used for that particular method, the driver was built as partial classes so people can exclude the pieces they don't need/want to save memory and space. Albeit not much, but when you're talking kilobytes of ram, every k counts.

**Comment by veccsolutions** [comment]
Thanks for your pull request

**Comment by veccsolutions** [comment]
pull #3
